INSERT INTO programas_formacion 
(estado, nivel_formacion, fecha_finalizacion, etapa_ficha, sector_programa, nombre_ocupacion, codigo, nombre_programa, duracion_programa, sector_economico)
VALUES
('En ejecucion', 'TECNICO', '2027-02-28', 'LECTIVA', 'INDUSTRIA', 'Auxiliares de información y servicio al cliente', 135329, 'MARKETING DIGITAL PARA EL SISTEMA MODA', 2208, 'SERVICIOS'),
('En ejecucion', 'TECNICO', '2025-05-15', 'PRACTICA', 'INDUSTRIA', 'Mecánicos Industriales', 837101, 'MECANICA DE MAQUINARIA INDUSTRIAL', 2208, 'INDUSTRIA'),
('En ejecucion', 'TECNICO', '2025-05-15', 'LECTIVA', 'INDUSTRIA', 'Mecánicos Industriales', 837101, 'MECANICA DE MAQUINARIA INDUSTRIAL', 2208, 'INDUSTRIA'),
('En ejecucion', 'TECNICO', '2025-12-15', 'LECTIVA', 'INDUSTRIA', 'Oficiales de Construcción', 836136, 'CONSTRUCCION, MANTENIMIENTO Y REPARACION DE ESTRUCTURAS EN GUADUA', 2208, 'CONSTRUCCION'),
('En ejecucion', 'TECNOLÓGO', '2025-03-18', 'LECTIVA', 'INDUSTRIA', 'Técnicos en Construcción y Arquitectura', 223107, 'CONSTRUCCION DE INFRAESTRUCTURA VIAL', 3984, 'CONSTRUCCION'),
('En ejecucion', 'TECNICO', '2025-05-15', 'LECTIVA', 'INDUSTRIA', 'Auxiliares técnicos en electrónica', 839317, 'MANTENIMIENTO Y ENSAMBLE DE EQUIPOS ELECTRONICOS.', 2208, 'ELECTRICIDAD'),
('En ejecucion', 'TECNICO', '2025-09-09', 'LECTIVA', 'INDUSTRIA', 'Dibujantes Técnicos', 225224, 'DIBUJO DIGITAL DE ARQUITECTURA E INGENIERIA', 2208, 'SERVICIOS'),
('En ejecucion', 'TECNOLÓGO', '2025-05-06', 'SERVICIOS', 'INDUSTRIA', 'Mecánicos de vehículos automotores', 838109, 'MANTENIMIENTO DE VEHICULOS LIVIANOS', 2208, 'INDUSTRIA'),
('En ejecucion', 'TECNOLÓGO', '2025-05-06', 'INDUSTRIA', 'INDUSTRIA', 'Técnicos en Construcción y Arquitectura', 223104, 'CONSTRUCCION EN EDIFICACIONES.', 3984, 'CONSTRUCCION'),
('En ejecucion', 'TECNOLÓGO', '2025-05-06', 'INDUSTRIA', 'INDUSTRIA', 'Técnicos en mecánica y construcción mecánica', 223213, 'MANTENIMIENTO ELECTROMECANICO INDUSTRIAL.', 3984, 'INDUSTRIA'),
('En ejecucion', 'TECNICO', '2026-09-06', 'LECTIVA', 'INDUSTRIA', 'Oficiales de Construcción', 836137, 'MANTENIMIENTO Y REPARACION DE EDIFICACIONES.', 2208, 'CONSTRUCCION'),
('En ejecucion', 'TECNICO', '2025-12-11', 'LECTIVA', 'INDUSTRIA', 'Patronistas de Productos de Tela, Cuero y Piel', 524500, 'PATRONAJE INDUSTRIAL DE PRENDAS DE VESTIR', 2208, 'TEXTILES'),
('En ejecucion', 'TECNICO', '2025-12-25', 'SERVICIOS', 'INDUSTRIA', 'Electricistas de Vehículos Automotores', 838210, 'MANTENIMIENTO DE SISTEMAS DE PROPULSION ELECTRICA E HIBRIDA AUTOMOTRIZ.', 2208, 'ELECTRICIDAD'),
('En ejecucion', 'TECNICO', '2024-01-21', 'PRACTICA', 'INDUSTRIA', 'Electricistas Residenciales', 832202, 'INSTALACION DE SISTEMAS ELECTRICOS RESIDENCIALES Y COMERCIALES', 2208, 'ELECTRICIDAD'),
('En ejecucion', 'TECNICO', '2025-09-05', 'LECTIVA', 'INDUSTRIA', 'Técnicos en automatización e instrumentación', 224312, 'AUTOMATIZACION DE SISTEMAS MECATRONICOS', 3984, 'INDUSTRIA'),
('En ejecucion', 'TECNICO', '2025-09-05', 'LECTIVA', 'INDUSTRIA', 'Dibujantes Técnicos', 225220, 'DIBUJO MECANICO', 2208, 'SERVICIOS'),
('En ejecucion', 'TECNOLÓGO', '2026-03-12', 'LECTIVA', 'INDUSTRIA', 'Técnicos en Construcción y Arquitectura', 223104, 'CONSTRUCCION EN EDIFICACIONES.', 3984, 'CONSTRUCCION'),
('En ejecucion', 'TECNOLÓGO', '2026-03-12', 'LECTIVA', 'INDUSTRIA', 'Técnicos en automatización e instrumentación', 224312, 'AUTOMATIZACION DE SISTEMAS MECATRONICOS', 3984, 'INDUSTRIA'),
('En ejecucion', 'TECNOLÓGO', '2026-03-12', 'LECTIVA', 'INDUSTRIA', 'Supervisores de ajustadores de máquinas herramientas', 821100, 'PRODUCCION DE COMPONENTES MECANICOS CON MAQUINAS DE CONTROL NUMERICO COMPUTARIZADO', 3984, 'INDUSTRIA'),
('En ejecucion', 'TECNOLÓGO', '2026-07-28', 'LECTIVA', 'INDUSTRIA', 'Técnicos en mecánica y construcción mecánica', 223211, 'DESARROLLO DE COMPONENTES MECANICOS', 3984, 'INDUSTRIA'),
('En ejecucion', 'TECNOLÓGO', '2026-07-10', 'LECTIVA', 'INDUSTRIA', 'Técnicos en automatización e instrumentación', 224312, 'AUTOMATIZACION DE SISTEMAS MECATRONICOS', 3984, 'INDUSTRIA'),
('En ejecucion', 'TECNOLÓGO', '2026-03-12', 'LECTIVA', 'INDUSTRIA', 'Técnicos en Construcción y Arquitectura', 223104, 'CONSTRUCCION EN EDIFICACIONES.', 3984, 'CONSTRUCCION'),
('En ejecucion', 'TECNICO', '2025-02-26', 'LECTIVA', 'INDUSTRIA', 'Ajustadores y operadores de máquinas herramientas', 831102, 'OPERACION EN TORNO Y FRESADORA', 2208, 'CONSTRUCCION'),
('En ejecucion', 'TECNOLÓGO', '2025-12-10', 'LECTIVA', 'INDUSTRIA', 'Técnicos en Construcción y Arquitectura', 223104, 'CONSTRUCCION EN EDIFICACIONES.', 3984, 'CONSTRUCCION'),
('En ejecucion', 'TECNOLÓGO', '2026-03-12', 'LECTIVA', 'INDUSTRIA', 'Técnicos en automatización e instrumentación', 224315, 'MANTENIMIENTO DE AUTOMATISMOS INDUSTRIALES..', 3984, 'INDUSTRIA'),
('En ejecucion', 'TECNOLÓGO', '2026-03-12', 'LECTIVA', 'INDUSTRIA', 'Técnicos en automatización e instrumentación', 224315, 'MANTENIMIENTO DE AUTOMATISMOS INDUSTRIALES..', 3984, 'INDUSTRIA'),
('En ejecucion', 'TECNICO', '2025-12-29', 'LECTIVA', 'INDUSTRIA', 'Sastres, Modistos, Peleteros y Sombrereros', 842200, 'ELABORACION DE PRENDAS DE VESTIR SOBRE MEDIDAS', 2208, 'TEXTILES'),
('En ejecucion', 'TECNICO', '2025-11-11', 'LECTIVA', 'INDUSTRIA', 'Técnicos en automatización e instrumentación', 224315, 'MANTENIMIENTO DE AUTOMATISMOS INDUSTRIALES..', 2352, 'INDUSTRIA'),
('En ejecucion', 'TECNICO', '2025-11-11', 'LECTIVA', 'INDUSTRIA', 'Técnicos en automatización e instrumentación', 224315, 'MANTENIMIENTO DE AUTOMATISMOS INDUSTRIALES..', 2352, 'INDUSTRIA'),
('En ejecucion', 'TECNICO', '2025-11-11', 'LECTIVA', 'SERVICIOS', 'Ajustadores y operadores de máquinas herramientas', 831102, 'OPERACION EN TORNO Y FRESADORA', 2208, 'SERVICIOS'),
('En ejecucion', 'TECNICO', '2025-03-29', 'LECTIVA', 'INDUSTRIA', 'Auxiliares técnicos en electrónica', 839317, 'MANTENIMIENTO Y ENSAMBLE DE EQUIPOS ELECTRONICOS.', 2304, 'INDUSTRIA'),
('En ejecucion', 'TECNICO', '2025-11-12', 'LECTIVA', 'INDUSTRIA', 'Auxiliares técnicos en electrónica', 839317, 'MANTENIMIENTO Y ENSAMBLE DE EQUIPOS ELECTRONICOS.', 2304, 'INDUSTRIA'),
('En ejecucion', 'TECNICO', '2025-11-12', 'LECTIVA', 'SERVICIOS', 'Mecánicos de vehículos automotores', 838109, 'MANTENIMIENTO DE VEHICULOS LIVIANOS', 2208, 'INDUSTRIA'),
('En ejecucion', 'TECNICO', '2025-03-29', 'LECTIVA', 'INDUSTRIA', 'Oficiales de Construcción', 836138, 'CONSTRUCCION DE EDIFICACIONES', 2208, 'CONSTRUCCION'),
('En ejecucion', 'TECNICO', '2026-01-14', 'LECTIVA', 'SERVICIOS', 'Diseñadores de teatro, moda, exhibición y otros diseñadores creativos', 524300, 'DESARROLLO DE COLECCIONES PARA LA INDUSTRIA DE LA MODA.', 3984, 'TEXTILES'),
('En ejecucion', 'TECNICO', '2026-01-14', 'LECTIVA', 'SERVICIOS', 'Mecánicos de Motos', 838318, 'MANTENIMIENTO DE MOTOCICLETAS Y MOTOCARROS.', 2208, 'INDUSTRIA'),
('En ejecucion', 'TECNICO', '2025-12-15', 'LECTIVA', 'INDUSTRIA', 'Oficiales de Construcción', 836138, 'CONSTRUCCION, MANTENIMIENTO Y REPARACION DE ESTRUCTURAS EN GUADUA', 2208, 'CONSTRUCCION'),
('En ejecucion', 'TECNICO', '2025-12-29', 'LECTIVA', 'INDUSTRIA', 'Sastres, Modistos, Peleteros y Sombrereros', 842200, 'ELABORACION DE PRENDAS DE VESTIR SOBRE MEDIDAS', 2208, 'TEXTILES'),
('En ejecucion', 'TECNICO', '2026-03-06', 'LECTIVA', 'SERVICIOS', 'Mecánicos de Motos', 838318, 'MANTENIMIENTO DE MOTOCICLETAS Y MOTOCARROS.', 2208, 'INDUSTRIA'),
('En ejecucion', 'TECNOLÓGO', '2025-12-15', 'LECTIVA', 'INDUSTRIA', 'Técnicos en Construcción y Arquitectura', 223104, 'CONSTRUCCION EN EDIFICACIONES.', 3984, 'CONSTRUCCION'),
('En ejecucion', 'TECNOLÓGO', '2025-04-27', 'LECTIVA', 'INDUSTRIA', 'Instaladores Residenciales y Comerciales', 841100, 'CARPINTERIA DE ALUMINIO', 1792, 'SERVICIOS'),
('En ejecucion', 'TECNOLÓGO', '2025-04-29', 'LECTIVA', 'INDUSTRIA', 'Sastres, Modistos, Peleteros y Sombrereros', 842200, 'ELABORACION DE PRENDAS DE VESTIR SOBRE MEDIDAS', 2208, 'TEXTILES'),
('En ejecucion', 'TECNOLÓGO', '2025-04-26', 'LECTIVA', 'INDUSTRIA', 'Electricistas Residenciales', 832202, 'INSTALACION DE SISTEMAS ELECTRICOS RESIDENCIALES Y COMERCIALES', 2208, 'ELECTRICIDAD'),
('En ejecucion', 'TECNOLÓGO', '2026-03-12', 'LECTIVA', 'INDUSTRIA', 'Supervisores de electricidad y telecomunicaciones', 821222, 'ELECTRICIDAD INDUSTRIAL', 3984, 'ELECTRICIDAD'),
('En ejecucion', 'TECNOLÓGO', '2025-09-05', 'LECTIVA', 'INDUSTRIA', 'Diseñadores de teatro, moda, exhibición y otros diseñadores creativos', 524300, 'DESARROLLO DE COLECCIONES PARA LA INDUSTRIA DE LA MODA.', 3984, 'TEXTILES'),
('En ejecucion', 'TECNOLÓGO', '2025-09-05', 'LECTIVA', 'INDUSTRIA', 'Electricistas Residenciales', 832202, 'INSTALACION DE SISTEMAS ELECTRICOS RESIDENCIALES Y COMERCIALES', 2208, 'ELECTRICIDAD'),
('En ejecucion', 'TECNICO', '2025-11-15', 'LECTIVA', 'INDUSTRIA', 'Auxiliares técnicos en electrónica', 839317, 'MANTENIMIENTO Y ENSAMBLE DE EQUIPOS ELECTRONICOS.', 2304, 'ELECTRICIDAD'),
('En ejecucion', 'TECNICO', '2025-11-15', 'LECTIVA', 'INDUSTRIA', 'Técnicos en automatización e instrumentación', 224315, 'MANTENIMIENTO DE AUTOMATISMOS INDUSTRIALES..', 2352, 'INDUSTRIA'),
('En ejecucion', 'TECNICO', '2025-11-15', 'LECTIVA', 'INDUSTRIA', 'Técnicos en automatización e instrumentación', 224315, 'MANTENIMIENTO DE AUTOMATISMOS INDUSTRIALES..', 2352, 'INDUSTRIA'),
('En ejecucion', 'TECNICO', '2026-03-16', 'PRACTICA', 'SERVICIOS', 'Supervisores de Fabricación de Productos de Tela, Cuero y Piel', 922500, 'SUPERVISION EN PROCESOS DE CONFECCION', 3984, 'TEXTILES'),
('En ejecucion', 'TECNICO', '2025-12-15', 'LECTIVA', 'INDUSTRIA', 'Operadores de Cámara de Cine y Televisión', 522211, 'ELABORACION DE AUDIOVISUALES.', 2208, 'SERVICIOS'),
('En ejecucion', 'TECNICO', '2025-11-12', 'LECTIVA', 'INDUSTRIA', 'Oficiales de Construcción', 836138, 'CONSTRUCCION DE EDIFICACIONES', 2208, 'CONSTRUCCION'),
('En ejecucion', 'TECNICO', '2025-11-12', 'SERVICIOS', 'INDUSTRIA', 'Operadores de Cámara de Cine y Televisión', 522211, 'ELABORACION DE AUDIOVISUALES.', 2208, 'SERVICIOS'),
('En ejecucion', 'TECNICO', '2025-11-12', 'LECTIVA', 'INDUSTRIA', 'Operadores de Cámara de Cine y Televisión', 522211, 'ELABORACION DE AUDIOVISUALES.', 2208, 'SERVICIOS'),
('En ejecucion', 'TECNICO', '2025-11-12', 'LECTIVA', 'INDUSTRIA', 'Operadores de Máquina Herramientas', 941106, 'MECANIZADO EN TORNO Y FRESADORA CONVENCIONAL', 2208, 'INDUSTRIA'),
('En ejecucion', 'TECNICO', '2025-11-12', 'LECTIVA', 'SERVICIOS', 'Operadores de Máquina Herramientas', 941106, 'MECANIZADO EN TORNO Y FRESADORA CONVENCIONAL', 2208, 'SERVICIOS'),
('En ejecucion', 'TECNICO', '2025-11-12', 'LECTIVA', 'INDUSTRIA', 'Auxiliares técnicos en electrónica', 839317, 'MANTENIMIENTO Y ENSAMBLE DE EQUIPOS ELECTRONICOS.', 2304, 'ELECTRICIDAD'),
('En ejecucion', 'TECNICO', '2025-11-12', 'LECTIVA', 'INDUSTRIA', 'Técnicos en automatización e instrumentación', 224312, 'MANTENIMIENTO DE AUTOMATISMOS INDUSTRIALES', 2352, 'INDUSTRIA'),
('En ejecucion', 'TECNICO', '2025-05-10', 'LECTIVA', 'SERVICIOS', 'Supervisores de mecánica', 821620, 'GESTION DEL MANTENIMIENTO DE AUTOMOTORES.', 3984, 'INDUSTRIA'),
('En ejecucion', 'TECNICO', '2025-07-14', 'LECTIVA', 'SERVICIOS', 'Productores, directores artísticos y ocupaciones relacionadas', 513101, 'PRODUCCION DE MEDIOS AUDIOVISUALES DIGITALES', 3984, 'SERVICIOS'),
('En ejecucion', 'TECNICO', '2025-07-14', 'LECTIVA', 'INDUSTRIA', 'Pintores y Empapeladores', 836600, 'PINTURA ARQUITECTONICA Y ACABADOS ESPECIALES', 2208, 'CONSTRUCCION'),
('En ejecucion', 'TECNICO', '2025-07-14', 'LECTIVA', 'SERVICIOS', 'Dibujantes Técnicos', 225224, 'DIBUJO DIGITAL DE ARQUITECTURA E INGENIERIA', 2208, 'SERVICIOS'),
('En ejecucion', 'TECNOLÓGO', '2025-07-14', 'LECTIVA', 'SERVICIOS', 'Pintores, escultores y otros artistas visuales', 513601, 'ANIMACION DIGITAL', 3984, 'SERVICIOS'),
('En ejecucion', 'TECNOLÓGO', '2025-07-14', 'LECTIVA', 'INDUSTRIA', 'Soldadores', 836138, 'CONSTRUCCION DE EDIFICACIONES', 2208, 'CONSTRUCCION'),
('En ejecucion', 'TECNOLÓGO', '2025-07-14', 'LECTIVA', 'INDUSTRIA', 'Técnicos en Construcción y Arquitectura', 223104, 'CONSTRUCCION EN EDIFICACIONES', 3984, 'CONSTRUCCION'),
('En ejecucion', 'TECNOLÓGO', '2025-07-14', 'LECTIVA', 'INDUSTRIA', 'Diseñadores de teatro, moda, exhibición y otros diseñadores creativos', 524300, 'DESARROLLO DE COLECCIONES PARA LA INDUSTRIA DE LA MODA.', 3984, 'TEXTILES'),
('En ejecucion', 'TECNOLÓGO', '2025-07-14', 'LECTIVA', 'INDUSTRIA', 'Técnicos en Diseño y Arte Gráfico', 522309, 'DESARROLLO DE MEDIOS GRAFICOS VISUALES', 3984, 'INDUSTRIA'),
('En ejecucion', 'TECNOLÓGO', '2025-07-22', 'LECTIVA', 'INDUSTRIA', 'Supervisores de electricidad y telecomunicaciones', 821222, 'ELECTRICIDAD INDUSTRIAL', 3984, 'ELECTRICIDAD'),
('En ejecucion', 'TECNOLÓGO', '2025-07-22', 'LECTIVA', 'INDUSTRIA', 'Soldadores', 836138, 'MANTENIMIENTO DE MOTOCICLETAS Y MOTOCARROS.', 2208, 'INDUSTRIA'),
('En ejecucion', 'TECNOLÓGO', '2025-07-22', 'SERVICIOS', 'Auxiliares técnicos en electrónica', 839317, 'MANTENIMIENTO Y ENSAMBLE DE EQUIPOS ELECTRONICOS.', 2304, 'ELECTRICIDAD'),
('En ejecucion', 'TECNOLÓGO', '2025-07-22', 'LECTIVA', 'INDUSTRIA', 'Diseñadores de teatro, moda, exhibición y otros diseñadores creativos', 524300, 'DESARROLLO DE COLECCIONES PARA LA INDUSTRIA DE LA MODA.', 3984, 'TEXTILES'),
('En ejecucion', 'TECNOLÓGO', '2025-07-22', 'LECTIVA', 'INDUSTRIA', 'Mecánicos de motos', 838318, 'MANTENIMIENTO DE MOTOCICLETAS Y MOTOCARROS.', 2208, 'INDUSTRIA'),
('En ejecucion', 'TECNOLÓGO', '2025-07-22', 'LECTIVA', 'INDUSTRIA', 'Técnicos en mecánica y construcción mecánica', 223213, 'MANTENIMIENTO ELECTROMECANICO INDUSTRIAL .', 3984, 'INDUSTRIA'),
('En ejecucion', 'TECNOLÓGO', '2025-07-22', 'LECTIVA', 'INDUSTRIA', 'Patronistas de Productos de Tela, Cuero y Piel', 524500, 'PATRONAJE INDUSTRIAL DE PRENDAS DE VESTIR', 2208, 'TEXTILES'),
('En ejecucion', 'TECNOLÓGO', '2025-07-22', 'LECTIVA', 'INDUSTRIA', 'Técnicos en automatización e instrumentación', 224315, 'MANTENIMIENTO DE AUTOMATISMOS INDUSTRIALES..', 2352, 'INDUSTRIA'),
('En ejecucion', 'TECNOLÓGO', '2025-07-22', 'LECTIVA', 'INDUSTRIA', 'Técnicos en automatización e instrumentación', 224315, 'MANTENIMIENTO DE AUTOMATISMOS INDUSTRIALES..', 2352, 'INDUSTRIA'),
('En ejecucion', 'TECNOLÓGO', '2025-07-22', 'LECTIVA', 'INDUSTRIA', 'Auxiliares técnicos en electrónica', 839317, 'MANTENIMIENTO Y ENSAMBLE DE EQUIPOS ELECTRONICOS.', 2304, 'ELECTRICIDAD'),
('En ejecucion', 'TECNOLÓGO', '2025-07-22', 'LECTIVA', 'INDUSTRIA', 'Técnicos en automatización e instrumentación', 224312, 'MANTENIMIENTO DE AUTOMATISMOS INDUSTRIALES', 2352, 'INDUSTRIA'),
('En ejecucion', 'TECNICO', '2025-07-10', 'LECTIVA', 'SERVICIOS', 'Supervisores de mecánica', 821620, 'GESTION DEL MANTENIMIENTO DE AUTOMOTORES.', 3984, 'INDUSTRIA'),
('En ejecucion', 'TECNICO', '2025-07-14', 'LECTIVA', 'SERVICIOS', 'Productores, directores artísticos y ocupaciones relacionadas', 513101, 'PRODUCCION DE MEDIOS AUDIOVISUALES DIGITALES', 3984, 'SERVICIOS'),
('En ejecucion', 'TECNICO', '2025-07-14', 'LECTIVA', 'INDUSTRIA', 'Pintores y Empapeladores', 836600, 'PINTURA ARQUITECTONICA Y ACABADOS ESPECIALES', 2208, 'CONSTRUCCION'),
('En ejecucion', 'TECNICO', '2025-07-14', 'LECTIVA', 'SERVICIOS', 'Dibujantes Técnicos', 225224, 'DIBUJO DIGITAL DE ARQUITECTURA E INGENIERIA', 2208, 'SERVICIOS'),
('En ejecucion', 'TECNOLÓGO', '2025-07-14', 'LECTIVA', 'SERVICIOS', 'Pintores, escultores y otros artistas visuales', 513601, 'ANIMACION DIGITAL', 3984, 'SERVICIOS'),
('En ejecucion', 'TECNOLÓGO', '2025-07-14', 'LECTIVA', 'INDUSTRIA', 'Soldadores', 836138, 'CONSTRUCCION DE EDIFICACIONES', 2208, 'CONSTRUCCION'),
('En ejecucion', 'TECNOLÓGO', '2025-07-14', 'LECTIVA', 'INDUSTRIA', 'Técnicos en Construcción y Arquitectura', 223104, 'CONSTRUCCION EN EDIFICACIONES', 3984, 'CONSTRUCCION'),
('En ejecucion', 'TECNOLÓGO', '2025-07-14', 'LECTIVA', 'INDUSTRIA', 'Diseñadores de teatro, moda, exhibición y otros diseñadores creativos', 524300, 'DESARROLLO DE COLECCIONES PARA LA INDUSTRIA DE LA MODA.', 3984, 'TEXTILES'),
('En ejecucion', 'TECNOLÓGO', '2025-07-14', 'LECTIVA', 'INDUSTRIA', 'Técnicos en Diseño y Arte Gráfico', 522309, 'DESARROLLO DE MEDIOS GRAFICOS VISUALES', 3984, 'INDUSTRIA'),
('En ejecucion', 'TECNOLÓGO', '2025-07-22', 'LECTIVA', 'INDUSTRIA', 'Supervisores de electricidad y telecomunicaciones', 821222, 'ELECTRICIDAD INDUSTRIAL', 3984, 'ELECTRICIDAD'),
('En ejecucion', 'TECNOLÓGO', '2025-07-22', 'LECTIVA', 'INDUSTRIA', 'Soldadores', 836138, 'MANTENIMIENTO DE MOTOCICLETAS Y MOTOCARROS.', 2208, 'INDUSTRIA'),
('En ejecucion', 'TECNOLÓGO', '2025-07-22', 'SERVICIOS', 'Auxiliares técnicos en electrónica', 839317, 'MANTENIMIENTO Y ENSAMBLE DE EQUIPOS ELECTRONICOS.', 2304, 'ELECTRICIDAD'),
('En ejecucion', 'TECNOLÓGO', '2025-07-22', 'LECTIVA', 'INDUSTRIA', 'Diseñadores de teatro, moda, exhibición y otros diseñadores creativos', 524300, 'DESARROLLO DE COLECCIONES PARA LA INDUSTRIA DE LA MODA.', 3984, 'TEXTILES'),
('En ejecucion', 'TECNOLÓGO', '2025-07-22', 'LECTIVA', 'INDUSTRIA', 'Mecánicos de motos', 838318, 'MANTENIMIENTO DE MOTOCICLETAS Y MOTOCARROS.', 2208, 'INDUSTRIA'),
('En ejecucion', 'TECNOLÓGO', '2025-07-22', 'LECTIVA', 'INDUSTRIA', 'Técnicos en mecánica y construcción mecánica', 223213, 'MANTENIMIENTO ELECTROMECANICO INDUSTRIAL .', 3984, 'INDUSTRIA'),
('En ejecucion', 'TECNOLÓGO', '2025-07-22', 'LECTIVA', 'INDUSTRIA', 'Patronistas de Productos de Tela, Cuero y Piel', 524500, 'PATRONAJE INDUSTRIAL DE PRENDAS DE VESTIR', 2208, 'TEXTILES'),
('En ejecucion', 'TECNOLÓGO', '2025-07-22', 'LECTIVA', 'INDUSTRIA', 'Técnicos en automatización e instrumentación', 224315, 'MANTENIMIENTO DE AUTOMATISMOS INDUSTRIALES..', 2352, 'INDUSTRIA'),
('En ejecucion', 'TECNOLÓGO', '2025-07-22', 'LECTIVA', 'INDUSTRIA', 'Técnicos en automatización e instrumentación', 224315, 'MANTENIMIENTO DE AUTOMATISMOS INDUSTRIALES..', 2352, 'INDUSTRIA'),
('En ejecucion', 'TECNOLÓGO', '2025-07-22', 'LECTIVA', 'INDUSTRIA', 'Auxiliares técnicos en electrónica', 839317, 'MANTENIMIENTO Y ENSAMBLE DE EQUIPOS ELECTRONICOS.', 2304, 'ELECTRICIDAD'),
('En ejecucion', 'TECNOLÓGO', '2025-07-22', 'LECTIVA', 'INDUSTRIA', 'Técnicos en automatización e instrumentación', 224312, 'MANTENIMIENTO DE AUTOMATISMOS INDUSTRIALES', 2352, 'INDUSTRIA'),
('En ejecucion', 'TÉCNICO', '2026-12-11', 'LECTIVA', 'INDUSTRIA', 'Técnicos en automatización e instrumentación', 224315, 'MANTENIMIENTO DE AUTOMATISMOS INDUSTRIALES..', 2352, 'INDUSTRIA'),
('En ejecucion', 'TECNÓLOGO', '2026-03-16', 'PRACTICA', 'INDUSTRIA', 'Supervisores de Fabricación de Productos de Tela, Cuero y Piel', 922500, 'SUPERVISION EN PROCESOS DE CONFECCION', 3984, 'TEXTILES'),
('En ejecucion', 'TÉCNICO', '2025-12-15', 'LECTIVA', 'SERVICIOS', 'Operadores de Cámara de Cine y Televisión', 522211, 'ELABORACION DE AUDIOVISUALES.', 2208, 'SERVICIOS'),
('En ejecucion', 'TÉCNICO', '2025-12-15', 'LECTIVA', 'INDUSTRIA', 'Oficiales de Construcción', 836138, 'CONSTRUCCION DE EDIFICACIONES', 2208, 'CONSTRUCCION'),
('En ejecucion', 'TÉCNICO', '2026-12-11', 'LECTIVA', 'INDUSTRIA', 'Ajustadores y operadores de máquinas herramientas', 831102, 'OPERACION EN TORNO Y FRESADORA', 2208, 'INDUSTRIA'),
('En ejecucion', 'TÉCNICO', '2025-12-15', 'LECTIVA', 'INDUSTRIA', 'Auxiliares técnicos en electrónica', 839317, 'MANTENIMIENTO Y ENSAMBLE DE EQUIPOS ELECTRONICOS.', 2304, 'ELECTRICIDAD'),
('En ejecucion', 'TÉCNICO', '2025-12-15', 'LECTIVA', 'INDUSTRIA', 'Patronistas de Productos de Tela, Cuero y Piel', 524500, 'PATRONAJE INDUSTRIAL DE PRENDAS DE VESTIR', 2208, 'TEXTILES'),
('En ejecucion', 'TECNÓLOGO', '2026-07-15', 'LECTIVA', 'INDUSTRIA', 'Supervisores de electricidad y telecomunicaciones', 821222, 'ELECTRICIDAD INDUSTRIAL', 3984, 'ELECTRICIDAD'),
('En ejecucion', 'TÉCNICO', '2025-12-15', 'LECTIVA', 'INDUSTRIA', 'Auxiliares técnicos en electrónica', 839317, 'MANTENIMIENTO Y ENSAMBLE DE EQUIPOS ELECTRONICOS.', 2304, 'ELECTRICIDAD'),
('En ejecucion', 'TÉCNICO', '2026-12-11', 'LECTIVA', 'SERVICIOS', 'Operadores de Cámara de Cine y Televisión', 522211, 'ELABORACION DE AUDIOVISUALES.', 2208, 'SERVICIOS'),
('En ejecucion', 'TÉCNICO', '2025-12-15', 'LECTIVA', 'INDUSTRIA', 'Oficiales de Construcción', 836138, 'CONSTRUCCION DE EDIFICACIONES', 2208, 'CONSTRUCCION'),
('En ejecucion', 'TÉCNICO', '2026-12-11', 'LECTIVA', 'INDUSTRIA', 'Oficiales de Construcción', 836138, 'CONSTRUCCION DE EDIFICACIONES', 2208, 'CONSTRUCCION'),
('En ejecucion', 'TÉCNICO', '2025-12-15', 'LECTIVA', 'SERVICIOS', 'Operadores de Cámara de Cine y Televisión', 522211, 'ELABORACION DE AUDIOVISUALES.', 2208, 'SERVICIOS'),
('En ejecucion', 'TÉCNICO', '2025-12-15', 'LECTIVA', 'SERVICIOS', 'Operadores de Cámara de Cine y Televisión', 522211, 'ELABORACION DE AUDIOVISUALES.', 2208, 'SERVICIOS'),
('En ejecucion', 'TÉCNICO', '2025-12-15', 'LECTIVA', 'INDUSTRIA', 'Operadores de Máquinas Herramientas', 941106, 'MECANIZADO EN TORNO Y FRESADORA CONVENCIONAL', 2208, 'INDUSTRIA'),
('En ejecucion', 'TÉCNICO', '2025-12-15', 'LECTIVA', 'INDUSTRIA', 'Oficiales de Construcción', 836138, 'CONSTRUCCION DE EDIFICACIONES', 2208, 'CONSTRUCCION'),
('En ejecucion', 'TÉCNICO', '2025-12-15', 'LECTIVA', 'SERVICIOS', 'Operadores de Cámara de Cine y Televisión', 522211, 'ELABORACION DE AUDIOVISUALES.', 2208, 'SERVICIOS'),
('En ejecucion', 'TÉCNICO', '2025-12-15', 'LECTIVA', 'INDUSTRIA', 'Operadores de Máquinas Herramientas', 941106, 'MECANIZADO EN TORNO Y FRESADORA CONVENCIONAL', 2208, 'INDUSTRIA'),
('En ejecucion', 'TÉCNICO', '2025-12-15', 'LECTIVA', 'INDUSTRIA', 'Auxiliares técnicos en electrónica', 839317, 'MANTENIMIENTO Y ENSAMBLE DE EQUIPOS ELECTRONICOS.', 2304, 'ELECTRICIDAD'),
('En ejecucion', 'TECNÓLOGO', '2026-07-14', 'LECTIVA', 'INDUSTRIA', 'Técnicos en automatización e instrumentación', 224312, 'AUTOMATIZACION DE SISTEMAS MECATRONICOS', 3984, 'INDUSTRIA'),
('En ejecucion', 'TECNÓLOGO', '2027-05-10', 'LECTIVA', 'SERVICIOS', 'Supervisores de mecánica', 821620, 'GESTION DEL MANTENIMIENTO DE AUTOMOTORES.', 3984, 'INDUSTRIA'),
('En ejecucion', 'TECNÓLOGO', '2026-10-07', 'LECTIVA', 'SERVICIOS', 'Productores, directores artísticos y ocupaciones relacionadas', 513101, 'PRODUCCION DE MEDIOS AUDIOVISUALES DIGITALES', 3984, 'SERVICIOS'),
('En ejecucion', 'TÉCNICO', '2025-07-14', 'LECTIVA', 'INDUSTRIA', 'Pintores y Empapeladores', 836600, 'PINTURA ARQUITECTONICA Y ACABADOS ESPECIALES', 2208, 'CONSTRUCCION'),
('En ejecucion', 'TÉCNICO', '2026-05-10', 'LECTIVA', 'INDUSTRIA', 'Dibujantes Técnicos', 225224, 'DIBUJO DIGITAL DE ARQUITECTURA E INGENIERIA', 2208, 'SERVICIOS'),
('En ejecucion', 'TÉCNICO', '2025-07-14', 'LECTIVA', 'INDUSTRIA', 'Topógrafos', 225314, 'CATASTRO MULTIPROPOSITO', 2208, 'CONSTRUCCION'),
('En ejecucion', 'TECNÓLOGO', '2026-07-14', 'LECTIVA', 'SERVICIOS', 'Productores, directores artísticos y ocupaciones relacionadas', 513101, 'PRODUCCION DE MEDIOS AUDIOVISUALES DIGITALES', 3984, 'SERVICIOS'),
('En ejecucion', 'TECNÓLOGO', '2026-07-14', 'LECTIVA', 'SERVICIOS', 'Pintores, escultores y otros artistas visuales', 513601, 'ANIMACION DIGITAL', 3984, 'SERVICIOS'),
('En ejecucion', 'TÉCNICO', '2026-12-11', 'LECTIVA', 'INDUSTRIA', 'Oficiales de Construcción', 836138, 'CONSTRUCCION DE EDIFICACIONES', 2208, 'CONSTRUCCION'),
('En ejecucion', 'TECNÓLOGO', '2027-01-14', 'LECTIVA', 'INDUSTRIA', 'Técnicos en Construcción y Arquitectura', 223104, 'CONSTRUCCION EN EDIFICACIONES.', 3984, 'CONSTRUCCION'),
('En ejecucion', 'TECNÓLOGO', '2026-07-14', 'LECTIVA', 'INDUSTRIA', 'Diseñadores de teatro, moda, exhibición y otros diseñadores creativos', 524300, 'DESARROLLO DE COLECCIONES PARA LA INDUSTRIA DE LA MODA.', 3984, 'TEXTILES'),
('En ejecucion', 'TÉCNICO', '2025-07-14', 'PRACTICA', 'INDUSTRIA', 'Soldadores', 834258, 'SOLDADURA DE PRODUCTOS METALICOS EN PLATINA', 2208, 'INDUSTRIA'),
('En ejecucion', 'TÉCNICO', '2026-01-14', 'LECTIVA', 'INDUSTRIA', 'Electricistas Industriales', 832102, 'ELECTRICISTA INDUSTRIAL', 2208, 'ELECTRICIDAD'),
('En ejecucion', 'TECNÓLOGO', '2027-05-10', 'LECTIVA', 'INDUSTRIA', 'Técnicos en automatización e instrumentación', 224312, 'AUTOMATIZACION DE SISTEMAS MECATRONICOS', 3984, 'INDUSTRIA'),
('En ejecucion', 'TÉCNICO', '2025-04-21', 'PRACTICA', 'INDUSTRIA', 'Soldadores', 834258, 'SOLDADURA DE PRODUCTOS METALICOS EN PLATINA', 2208, 'INDUSTRIA'),
('En ejecucion', 'TECNÓLOGO', '2026-07-14', 'LECTIVA', 'INDUSTRIA', 'Técnicos en mecánica y construcción mecánica', 223213, 'MANTENIMIENTO ELECTROMECANICO INDUSTRIAL .', 3984, 'INDUSTRIA'),
('En ejecucion', 'TÉCNICO', '2026-05-10', 'LECTIVA', 'INDUSTRIA', 'Técnicos de aire acondicionado y refrigeración', 837501, 'MANTENIMIENTO DE EQUIPOS DE AIRE ACONDICIONADO Y REFRIGERACION', 2208, 'INDUSTRIA'),
('En ejecucion', 'TECNÓLOGO', '2026-10-07', 'LECTIVA', 'SERVICIOS', 'Productores, directores artísticos y ocupaciones relacionadas', 513101, 'PRODUCCION DE MEDIOS AUDIOVISUALES DIGITALES', 3984, 'SERVICIOS'),
('En ejecucion', 'TECNÓLOGO', '2027-05-10', 'LECTIVA', 'INDUSTRIA', 'Supervisores de electricidad y telecomunicaciones', 821222, 'ELECTRICIDAD INDUSTRIAL', 3984, 'ELECTRICIDAD'),
('En ejecucion', 'TECNÓLOGO', '2026-10-07', 'LECTIVA', 'INDUSTRIA', 'Técnicos en mecánica y construcción mecánica', 223213, 'MANTENIMIENTO ELECTROMECANICO INDUSTRIAL .', 3984, 'INDUSTRIA'),
('En ejecucion', 'TECNÓLOGO', '2026-04-21', 'LECTIVA', 'INDUSTRIA', 'Técnicos en electrónica', 224201, 'DESARROLLO DE SISTEMAS ELECTRONICOS INDUSTRIALES', 3984, 'ELECTRICIDAD'),
('En ejecucion', 'TECNÓLOGO', '2026-10-07', 'LECTIVA', 'INDUSTRIA', 'Supervisores de electricidad y telecomunicaciones', 821222, 'ELECTRICIDAD INDUSTRIAL', 3984, 'ELECTRICIDAD'),
('En ejecucion', 'TECNÓLOGO', '2025-07-16', 'LECTIVA', 'INDUSTRIA', 'Técnicos en automatización e instrumentación', 224312, 'AUTOMATIZACION DE SISTEMAS MECATRONICOS', 3984, 'INDUSTRIA'),
('En ejecucion', 'TECNÓLOGO', '2025-04-22', 'LECTIVA', 'SERVICIOS', 'Pintores, escultores y otros artistas visuales', 513601, 'ANIMACION DIGITAL', 3984, 'SERVICIOS'),
('En ejecucion', 'TÉCNICO', '2026-05-10', 'LECTIVA', 'INDUSTRIA', 'Soldadores', 834258, 'SOLDADURA DE PRODUCTOS METALICOS EN PLATINA', 2208, 'INDUSTRIA'),
('En ejecucion', 'TÉCNICO', '2025-10-07', 'LECTIVA', 'INDUSTRIA', 'Dibujantes Técnicos', 225224, 'DIBUJO DIGITAL DE ARQUITECTURA E INGENIERIA', 2208, 'SERVICIOS'),
('En ejecucion', 'TECNÓLOGO', '2026-04-21', 'LECTIVA', 'SERVICIOS', 'Pintores, escultores y otros artistas visuales', 513601, 'ANIMACION DIGITAL', 3984, 'SERVICIOS'),
('En ejecucion', 'TECNÓLOGO', '2026-07-14', 'LECTIVA', 'INDUSTRIA', 'Supervisores de electricidad y telecomunicaciones', 821222, 'ELECTRICIDAD INDUSTRIAL', 3984, 'ELECTRICIDAD'),
('En ejecucion', 'TÉCNICO', '2025-10-07', 'LECTIVA', 'INDUSTRIA', 'Electricistas Residenciales', 832202, 'INSTALACION DE SISTEMAS ELECTRICOS RESIDENCIALES Y COMERCIALES', 2208, 'ELECTRICIDAD'),
('En ejecucion', 'TÉCNICO', '2026-12-11', 'LECTIVA', 'INDUSTRIA', 'Oficiales de Construcción', 836138, 'CONSTRUCCION DE EDIFICACIONES', 2208, 'CONSTRUCCION'),
('En ejecucion', 'TECNÓLOGO', '2025-12-31', 'LECTIVA', 'INDUSTRIA', 'Diseñadores de teatro, moda, exhibición y otros diseñadores creativos', 524300, 'DESARROLLO DE COLECCIONES PARA LA INDUSTRIA DE LA MODA.', 3984, 'TEXTILES'),
('En ejecucion', 'TÉCNICO', '2026-05-10', 'LECTIVA', 'SERVICIOS', 'Electricistas de Vehículos Automotores', 838200, 'MANTENIMIENTO ELECTRICO Y CONTROL ELECTRONICO DE AUTOMOTORES', 2208, 'ELECTRICIDAD'),
('En ejecucion', 'TÉCNICO', '2025-12-15', 'LECTIVA', 'INDUSTRIA', 'Auxiliares de información y servicio al cliente', 135329, 'MARKETING DIGITAL PARA EL SISTEMA MODA', 2208, 'SERVICIOS'),
('En ejecucion', 'TÉCNICO', '2025-07-14', 'LECTIVA', 'INDUSTRIA', 'Electricistas Residenciales', 832202, 'INSTALACION DE SISTEMAS ELECTRICOS RESIDENCIALES Y COMERCIALES', 2208, 'ELECTRICIDAD'),
('En ejecucion', 'TÉCNICO', '2025-10-07', 'LECTIVA', 'INDUSTRIA', 'Patronistas de Productos de Tela, Cuero y Piel', 524500, 'PATRONAJE INDUSTRIAL DE PRENDAS DE VESTIR', 2208, 'TEXTILES'),
('En ejecucion', 'TÉCNICO', '2025-08-13', 'LECTIVA', 'INDUSTRIA', 'Patronistas de Productos de Tela, Cuero y Piel', 524500, 'PATRONAJE INDUSTRIAL DE PRENDAS DE VESTIR', 2208, 'TEXTILES'),
('En ejecucion', 'TÉCNICO', '2025-10-07', 'LECTIVA', 'INDUSTRIA', 'Oficiales de Construcción', 836135, 'CONSTRUCCIONES LIVIANAS INDUSTRIALIZADAS EN SECO', 2208, 'CONSTRUCCION'),
('En ejecucion', 'TECNÓLOGO', '2025-12-31', 'LECTIVA', 'INDUSTRIA', 'Dibujantes Técnicos', 225219, 'DIBUJO Y MODELADO ARQUITECTONICO Y DE INGENIERIA', 3984, 'SERVICIOS'),
('En ejecucion', 'TÉCNICO', '2025-04-21', 'LECTIVA', 'SERVICIOS', 'Técnicos de aire acondicionado y refrigeración', 837530, 'MANTENIMIENTO DE EQUIPOS DE REFRIGERACION, VENTILACION Y CLIMATIZACION', 2205, 'INDUSTRIA'),
('En ejecucion', 'TÉCNICO', '2025-10-07', 'LECTIVA', 'INDUSTRIA', 'Auxiliares de información y servicio al cliente', 135329, 'MARKETING DIGITAL PARA EL SISTEMA MODA', 2208, 'SERVICIOS'),
('En ejecucion', 'TECNÓLOGO', '2025-12-31', 'LECTIVA', 'SERVICIOS', 'Productores, directores artísticos y ocupaciones relacionadas', 513101, 'PRODUCCION DE MEDIOS AUDIOVISUALES DIGITALES', 3984, 'SERVICIOS'),
('En ejecucion', 'TÉCNICO', '2025-10-07', 'LECTIVA', 'INDUSTRIA', 'Técnicos de aire acondicionado y refrigeración', 837501, 'MANTENIMIENTO DE EQUIPOS DE AIRE ACONDICIONADO Y REFRIGERACION', 2208, 'INDUSTRIA');
